// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Dpp5lPlLW5zNedI-JuKNUE5SK_oT48E',
    appId: '1:520231205785:web:fdbf905e27a75d80cc7108',
    messagingSenderId: '520231205785',
    projectId: 'jeleapps-c9836',
    authDomain: 'jeleapps-c9836.firebaseapp.com',
    storageBucket: 'jeleapps-c9836.appspot.com',
    measurementId: 'G-72KLWG04RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDCmbEVUnog0ixJipoBuaxyVkAMv5OEFI',
    appId: '1:520231205785:android:d8a06bacd5dba05bcc7108',
    messagingSenderId: '520231205785',
    projectId: 'jeleapps-c9836',
    storageBucket: 'jeleapps-c9836.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfXSO53M5mUUTBY1X89aE3ycOr-Ux8pjk',
    appId: '1:520231205785:ios:be238d578c4e533fcc7108',
    messagingSenderId: '520231205785',
    projectId: 'jeleapps-c9836',
    storageBucket: 'jeleapps-c9836.appspot.com',
    iosBundleId: 'com.jeleapps.jeleapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfXSO53M5mUUTBY1X89aE3ycOr-Ux8pjk',
    appId: '1:520231205785:ios:be238d578c4e533fcc7108',
    messagingSenderId: '520231205785',
    projectId: 'jeleapps-c9836',
    storageBucket: 'jeleapps-c9836.appspot.com',
    iosBundleId: 'com.jeleapps.jeleapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Dpp5lPlLW5zNedI-JuKNUE5SK_oT48E',
    appId: '1:520231205785:web:4cd58b85c77a7a30cc7108',
    messagingSenderId: '520231205785',
    projectId: 'jeleapps-c9836',
    authDomain: 'jeleapps-c9836.firebaseapp.com',
    storageBucket: 'jeleapps-c9836.appspot.com',
    measurementId: 'G-VXZVHE9PJC',
  );
}
